# Generated by Django 4.0 on 2021-12-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hacker_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hacker_ip', models.CharField(max_length=100)),
                ('attack_port', models.CharField(max_length=50)),
                ('attack_time', models.DateTimeField(auto_now_add=True)),
                ('honeybot_name', models.CharField(max_length=200)),
            ],
        ),
    ]
